### ISSUE TITLE
Organization signup/QA

### ISSUE THREAD

**Issue by justinxreese** [eventil/eventil.com#10]
Making sure I'm a useful beta user. Here's what I've found during the signup process.

On https://eventil.com/organizations/new
- [x] No field for `state` - this is expected by US orgs. Put mine in "city" field
- [x] "Desc" field label is ambiguous 
- [x] "Desc" field has placeholder that looks to be meant for an individual

On https://eventil.com/organizations/{id no}
- [ ] "Connect Stripe" link leads to page with only `{"error":{"message":"No application matches the supplied client identifier"}}`

Not sure where to go to add an event

**Comment by zaiste** [comment]
@justinxreese it's mostly done
