### ISSUE TITLE
Missing "Show past events" functionality

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#102]
I couldn't find how to show older events. Sometimes it's useful to look at events made in past. For now you have to know exact link or get there from user profile.

I'd like some option to find older events in search.

![screen shot 2016-09-30 at 22 28 23](https://cloud.githubusercontent.com/assets/33736/19005963/df7bdd56-874c-11e6-9d3e-e8ca565498d7.png)

**Comment by tomkuk** [comment]
@deepj it's available here `https://eventil.com/events?q%5Bpast%5D=true`
