### ISSUE TITLE
How to turn off / unsubscribe from Eventil emails?

### ISSUE THREAD

**Issue by justinclift** [eventil/eventil.com#104]
Just received a "Here are top 3 events for October" email.

How does a person turn these off?  There doesn't seem to be a way in Account Settings.

If that's not possible, how does a person remove their account?  Didn't see an option for that either.  :wink:

**Comment by tomkuk** [comment]
@justinclift 
you can turn off the mails here https://eventil.com/settings/email_settings
you can delete your account here  https://eventil.com/settings/account

**Comment by justinclift** [comment]
Thanks @tomkuk, I've just turned off all the checkboxes in the settings. :smile:

Is Eventil is back under development then?  If so, maybe adjust the footer on the site from 2017 to "2017-2018" too, to reinforce it's up-to-date-ness? :smile:

Hmmm, same for the Nukomeet website too, which is still 2015. :wink:

**Comment by tomkuk** [comment]
Thanks, we will update it
