### ISSUE TITLE
Additional talks

### ISSUE THREAD

**Issue by sgrove** [eventil/eventil.com#107]
Not sure how to add these myself in the UI, so opening an issue:

2015 ReactiveConf (Bratislava) [Dato — a functional way to build reactive applications](https://reactive2015.com/schedule_speakers.html#schedule)

2016 SeleniumConf India (Bangalore) [Generating and Running 1,000,000 Selenium tests in 60 minutes](https://confengine.com/selenium-conf-2016/proposal/2547/generating-and-running-1000000-selenium-tests-in-60-minutes)

2016 Curry On (Rome) [From Unikernels to Databases to UIs: Truly full-stack apps in OCaml](http://curry-on.org/2016/sessions/from-unikernels-to-databases-to-uis.html)

2016 ICFP/CUFP (Nara) [Baby steps to unikernels in production](http://cufp.org/2016/baby-steps-to-unikernels-in-production.html)

**Comment by zaiste** [comment]
@sgrove thanks! it's been just added, we're still working on the UI for users :)
