### ISSUE TITLE
One talk - two speakers

### ISSUE THREAD

**Issue by DianaGawel** [eventil/eventil.com#115]
There is no option for example in agenda to match two people with one talk, you have to mention it twice (each time with different speaker - it can be confusing for attendees)

**Comment by zaiste** [comment]
@DianaGawel yes we have to discuss how to implement this feature

**Comment by tomkuk** [comment]
@DianaGawel this should work, I think we can close it

**Comment by zaiste** [comment]
@DianaGawel can you confirm and close if OK ?

**Comment by DianaGawel** [comment]
@zaiste Yes, it OK
