### ISSUE TITLE
Talk Submission QA

### ISSUE THREAD

**Issue by justinxreese** [eventil/eventil.com#12]
I'm submitting a talk to see what it'll be like for people submitting a talk to Abstractions

Flow for completing bio before submitting a proposal is a little off-putting 

On `https://eventil.com/edit`
- [x] "Tags" field has HTML showing in its placeholder
- [x] Dislike "Tags" being required as the list is incomplete
- [x] Dislike Tagline being required because it's not always necessary
- [x] Dislike website being required - not everyone will have this
- [x] Dislike twitter being required - not everyone will have this
- [x] "Avatar" seems skewed toward a software-only crowd. My community/leadership submitters may be less confused by "Profile Picture"
- [x] **IMPORTANT Can't finish saving because "Tags" field can't be blank but doesn't persist**

Because of the last item in the above checklist, I am unable to submit a talk

**Comment by zaiste** [comment]
@justinxreese most of this should be done now, could you elaborate on the avatar issue ?

**Comment by justinxreese** [comment]
I just think the wording chosen is a little too specific to programmers. "Avatar" is an easy word for programmers, but not necessarily everyone. Was suggesting "Profile picture" instead.

**Comment by justinxreese** [comment]
- [x] "It will be added as a Bronze sponsor on the website" is not true for my event

**Comment by zaiste** [comment]
@justinxreese I'm closing this as all those issues have been resolved
