### ISSUE TITLE
Can't vote on an Event Poll (or find out how to vote)

### ISSUE THREAD

**Issue by caesarsol** [eventil/eventil.com#126]
From the page https://eventil.com/events/polyconf-17/poll it seems I can't go further in the voting process, there is no button to proceed nor things to click.

(Or there is nothing to vote on, in which case there should be a message)

Screenshot attached:

![screen shot 2017-03-21 at 23 13 02](https://cloud.githubusercontent.com/assets/1799710/24173377/11d0384e-0e8c-11e7-801d-58e2cd9da966.png)

**Comment by zaiste** [comment]
@caesarsol sorry about those issues, we are experiencing some small technical problems, there is a lot of submissions, we are working on making it easy to read through. We had to move the community voting to Friday. I'll let you know once it's ready.

**Comment by caesarsol** [comment]
@zaiste that's good to know, thanks!
