### ISSUE TITLE
Can't login with Github

### ISSUE THREAD

**Issue by blagberlin** [eventil/eventil.com#127]
I get a 422 error: Unprocessable Entity

**Comment by zaiste** [comment]
@blagberlin thanks for reporting it, we are checking it cc @kasiakasprzak

**Comment by zaiste** [comment]
@blagberlin it seems you already registered a regular account with the same email you has on GitHub. You can restore your password here: https://eventil.com/forgot/new

**Comment by zaiste** [comment]
@blagberlin have you managed to restore your password ?
