### ISSUE TITLE
Cannot reset password

### ISSUE THREAD

**Issue by webmajstr** [eventil/eventil.com#128]
I requested password reset around one hour ago, and still I did not get email for reseting password. My email has gmail.com domain.

**Comment by zaiste** [comment]
@webmajstr thanks, we are checking it cc @kasiakasprzak @2can

**Comment by zaiste** [comment]
@webmajstr the issue should be resolved, have you received the email ? if not, could you retry the reseting password ?

**Comment by webmajstr** [comment]
Yes, I confirm I got reset password emails. Thank you!
