### ISSUE TITLE
Votes: Distinguish between talk and workshop submissions

### ISSUE THREAD

**Issue by christophgockel** [eventil/eventil.com#129]
As a PolyConf attendee,
I would like to see whether a submission is a workshop or talk submission,
so that I can make an informed decision about what I want to vote on.

**Comment by gemcfadyen** [comment]
To add to this, Today I don't actually see any workshops listed in the vote. Workshops seem to be missing from the listings.

**Comment by zaiste** [comment]
@christophgockel @gemcfadyen Yes, we retracted them to avoid confusion as we only had a handful of those (4-5). It will be selected by the committee ;) - it'll be easier I think. Is that OK for you ?

**Comment by christophgockel** [comment]
Oh I see, that's cool! Thanks for the update!
