### ISSUE TITLE
How do I see the content of my own submission?

### ISSUE THREAD

**Issue by hamin** [eventil/eventil.com#132]
I have a submission that was rejected. I'm trying to get the abstract and notes for that submission that were submitted for the conference. All I see is the rejected submission but no link to view the details

**Comment by zaiste** [comment]
@hamin such feature does not exist but we will implement for you in the following days

**Comment by hamin** [comment]
@zaiste I'm actually trying to submit another CFP for another conference. Is there any chance support can email or send me my presentation info via email or something? I understand you haven't built the feature yet but I would really appreciate it. I should've saved the submission info locally :)

**Comment by hamin** [comment]
@zaiste who/where can I contact someone who could help me get that info on my submitted presentation? Is there a support email? Thanks

**Comment by zaiste** [comment]
@hamin just sent it your way
