### ISSUE TITLE
Ticket (Polyconf) not visible in Attendee settings / tickets

### ISSUE THREAD

**Issue by DanEEStar** [eventil/eventil.com#135]
Hello 

I bought a ticket for Polyconf on March 24.
I received the order confirmation with the account activation link on this day.

Today I wanted to print the ticket. But there is no ticket in my eventil account.
And there seems to be no other way to access the ticket?!

**Comment by DianaGawel** [comment]
Hi,
We are checking what's wrong. We will inform you asap.

Have a good day and see you at the conference!

**Comment by DianaGawel** [comment]
Hi,
Please tell me, did you buy the ticket via eventil or you paid by bank transfer? I also can't see the ticket on your eventil account.

**Comment by DanEEStar** [comment]
I bought the ticket via eventil.

Here are the details from the confirmation email:

Invoice no. OR-900/EV-39138/201703-13 
Order: OT14aLX8mAl3POZeWKO0qB

I bought the ticket with the email "daniel.egger@iterativ.ch" but my github email is "daniel.egger@gmail.com". Could that be a problem?

**Comment by DianaGawel** [comment]
It could cause the problem. I will check and let you know in a minute.

**Comment by DianaGawel** [comment]
Your ticket is on your account created with email daniel.egger@iterativ.ch. Can you log in and check?

**Comment by DanEEStar** [comment]
That was indeed it.
The ticket is under the daniel.egger@iterativ.ch account.

**Comment by DianaGawel** [comment]
Great. So you can | "use" your ticket from that account or if you wish, you can always transfer it to your other account in Settings --> Tickets. There is an option that you can assign it to someone and you can choose the account with the other email. As you wish.
