### ISSUE TITLE
Income amount is incorrect in orders if a coupon was applied

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#139]
An income amount is higher than a total amount when a coupon was applied. See the orders.

`income = total - eventil - stripe` so it wouldn't be possible in order to an income was higher than a total amount.

**Comment by kasiabernad** [comment]
@deepj is it about Dashboard tab in Event management?

**Comment by kasiabernad** [comment]
@deepj never mind, I got it - Event management tab 'Orders'..

**Comment by kasiabernad** [comment]
@deepj fixed.
