### ISSUE TITLE
Where do I find submissions?

### ISSUE THREAD

**Issue by justinxreese** [eventil/eventil.com#14]
Just submitted a test submission to my own event. Not sure where to look to review it.

**Comment by zaiste** [comment]
@justinxreese we've just added a « Talks » tab only visible to admins, where you can accept/reject each talk Could you check if you see it ? cc @hauleth

**Comment by hauleth** [comment]
Should be visible now for event organisers in « Talks » tab.

**Comment by zaiste** [comment]
@justinxreese `Submissions` are now in `Speaker -> Submissions` section
