### ISSUE TITLE
I'll be speaking at an event even my proposal was rejected

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#141]
This is wrong. When I tested to submit a proposal to an event, I can still see I'll be speaking at the event

**Actual**:
![screen shot 2017-06-01 at 17 06 06](https://cloud.githubusercontent.com/assets/33736/26686429/6312c5b8-46dc-11e7-8e5b-8122fbbe49e0.png)

![screen shot 2017-06-01 at 17 06 24](https://cloud.githubusercontent.com/assets/33736/26686430/637b0ef2-46dc-11e7-960f-46d271cd8d56.png)

**Expected**:
I'll see nothing in the events tab. Literally, zero events :)

**Comment by tomkuk** [comment]
@deepj it's fixed
