### ISSUE TITLE
Missing comma in location in presentations on the profile

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#142]
Compare

![screen shot 2017-06-01 at 17 06 06](https://cloud.githubusercontent.com/assets/33736/26687161/a2ca33d8-46de-11e7-8767-cdb85b156c90.png)
![screen shot 2017-06-01 at 17 06 24](https://cloud.githubusercontent.com/assets/33736/26687160/a28487e8-46de-11e7-8871-700fc13085ab.png)

**Actual**:
See location in the first screenshot. There is no comma between _Paris_ and France as in the second screenshot.

**Expected**:
_Paris, France_

**Comment by zaiste** [comment]
@deepj it's corrected
