### ISSUE TITLE
Missing translation for "Add to Calendar" on Event page

### ISSUE THREAD

**Issue by justinxreese** [eventil/eventil.com#146]
Hovering the "Add to Calendar" link on `https://eventil.com/events/event-slug` shows the following text: `translation missing: en.application.event_header.add_to_calendar` instead of an expected `Add to Calendar`

This is in the `banner-ticket` div, to help find it.

**Comment by 2can** [comment]
@justinxreese it's fixed and deployed

**Comment by justinxreese** [comment]
Confirmed that there's no longer `translation missing` text.
