### ISSUE TITLE
Two day event shows as one day on event page

### ISSUE THREAD

**Issue by justinxreese** [eventil/eventil.com#147]
In the `.banner-ticket` classed div where it shows the event date, multidate events only show as a single day.

**The event settings**

<img width="662" alt="image" src="https://user-images.githubusercontent.com/150839/33050319-51ba3d36-ce32-11e7-8d45-9a4bd65faedf.png">

**How that is displayed**

<img width="391" alt="image" src="https://user-images.githubusercontent.com/150839/33050311-48de90d6-ce32-11e7-8faa-fc38c72d6dc7.png">

This will be pretty confusing to potential attendees.

**Comment by 2can** [comment]
@justinxreese end date added, change deployed

@justinxreese we've seen you've tried to connect Stripe to [Heartifacts](https://eventil.com/events/heartifacts) , could you update `Code & Supply` organisation with `vatid` and try again ?

**Comment by justinxreese** [comment]
We don't have a VAT ID. We're an American organization that only holds
events in the US.

**Comment by 2can** [comment]
@justinxreese that field is used for invoicing to display seller Tax number which is required by law in some countries. Does your organization have Tax ID ?

**Comment by justinxreese** [comment]
Yup it does. I'll try that. I'll try in a few days because it's a holiday
here. Thanks for troubleshooting and reaching out.

**Comment by justinxreese** [comment]
That worked, @2can. Brings up some additional questions that I'll make issues for elsewhere
