### ISSUE TITLE
No documentation or way on how to remove my account and data from eventil

### ISSUE THREAD

**Issue by simcap** [eventil/eventil.com#148]
Eventil has to inform/document the steps one need to take to delete one's eventil account and remove the corresponding data.

**Comment by 2can** [comment]
@simcap I'm very sorry for inconvenience 

We'll update [docs](https://docs.eventil.com/) and put link to remove account in settings with the next release (by the end of this week). 

Are you willing to wait for this functionality or would you like to remove your account straight away?

**Comment by simcap** [comment]
Thanks. I will wait for the functionality and then follow along to check out if the process is good enough.

**Comment by 2can** [comment]
@simcap it's on production -> https://eventil.com/settings/account

**Comment by simcap** [comment]
Thanks. I cannot login anymore, so seems to have worked. Any ideas of what happens to my data? What is removed as well?

**Comment by 2can** [comment]
Data required for invoicing stays - Eventil provides invoicing for event organisers
