### ISSUE TITLE
Ticket prices only available in Euros

### ISSUE THREAD

**Issue by justinxreese** [eventil/eventil.com#149]
As a US based org selling to predominantly US based customers, the tickets showing in euros will be confusing to my audience. They may even double check the event is being held where they thought it was.

Is there a plan to support USD or other currencies soon?

**Comment by 2can** [comment]
@justinxreese yes, we'll activate it with next release (by the end of this week). Which currencies apart from USD do you need ?

**Comment by justinxreese** [comment]
Just need USD. Speaking for the general public there.

**Comment by 2can** [comment]
@justinxreese it's on production, you can have only one currency per event so for `Heartifacts` you should remove defined ticket in `EUR` and define it once again.

**Comment by justinxreese** [comment]
I'm given a "No access" error when I try to destroy a ticket. I'm able to edit it just fine. Should I create a separate issue for that or is it related to the change?

**Comment by 2can** [comment]
@justinxreese please try once again

- ticket can be destroyed only if there are no orders but if some session is opened (sb is in the process of buying ticket and session is in progress) it also blocks ticket removal

**Comment by justinxreese** [comment]
How long do the sessions survive? I don't think anyone would be buying one
so it must've been me.

**Comment by 2can** [comment]
Session lasts for 10mins, but it can impact ticket removal up to 1hour

**Comment by justinxreese** [comment]
Works now 👍
