### ISSUE TITLE
How to add speakers to an event where Eventil didn't manage the CfP

### ISSUE THREAD

**Issue by mikesperber** [eventil/eventil.com#151]
I've been stumped adding speaker information to the sessions for BOB:

https://eventil.com/events/bob-2018

We didn't manage the CfP process through eventil, so the list of speakers is empty. Any way I can add this?

**Comment by DianaGawel** [comment]
@mikesperber Hi Mike. We're still working on this functionality. I will add the speakers for your event today.

**Comment by DianaGawel** [comment]
@mikesperber I added speakers from your conference website to the event

**Comment by mikesperber** [comment]
Wow, thanks!
