### ISSUE TITLE
I've got newsletter despite i'm sign-off 

### ISSUE THREAD

**Issue by ArturKy** [eventil/eventil.com#152]
Hi!

I receive Your Newsletter despite, I've NEVER sign in to receive them.
I've ALWAYS have un-checked newsletter in email preferences. 
Please explain WHY I receive Your Newsletter?

![przechwytywanie](https://user-images.githubusercontent.com/15805253/34002399-cc970494-e0f2-11e7-896e-550cf7195173.JPG)
![przechwytywanie2](https://user-images.githubusercontent.com/15805253/34002402-ccf34da8-e0f2-11e7-95a2-aae2591de4a6.JPG)

**Comment by DianaGawel** [comment]
@ArturKy Hi Artur, we corrected your email setting. We will issue the next newsletter tomorrow so if by any chance you receive it again, please let me know. If you don't receive it, you can close the issue so that we know everything is OK.
