### ISSUE TITLE
I can't make one of the members of my group admin

### ISSUE THREAD

**Issue by elbrujohalcon** [eventil/eventil.com#153]
I'm the admin of https://eventil.com/groups/inakos
@fpereiro is a member of my organization and I want to make him admin.
This happens:
![](http://g.recordit.co/TuUBEqJDGp.gif)

**Comment by tomkuk** [comment]
@elbrujohalcon please try to choose only one role, we will fix it on our side to use proper select box

**Comment by elbrujohalcon** [comment]
@tomkuk sadly, it's not possible. You can see in the gif, when I try to just remove `member`, the system fails without allowing me to choose `admin`

**Comment by tomkuk** [comment]
@elbrujohalcon can you check it one more time ? we have just fixed it

**Comment by elbrujohalcon** [comment]
It's fixed, you rock @tomkuk !!
