### ISSUE TITLE
Can't see my tickets after you have taken my money

### ISSUE THREAD

**Issue by kaspergrubbe** [eventil/eventil.com#156]
<img width="527" alt="screenie_1519211865_393101" src="https://user-images.githubusercontent.com/334273/36478045-4bcc54ba-16fb-11e8-894d-67e50359b9ce.png">

<img width="750" alt="screenie_1519212032_348993" src="https://user-images.githubusercontent.com/334273/36478050-511c3868-16fb-11e8-8439-e3bdb762a427.png">

<img width="878" alt="screenie_1519212381_272897" src="https://user-images.githubusercontent.com/334273/36478060-5548f5ac-16fb-11e8-84aa-7303babe774b.png">

<img width="587" alt="screenie_1519212950_660741" src="https://user-images.githubusercontent.com/334273/36478105-78e54f92-16fb-11e8-8d90-135b2045fa0f.png">

<img width="768" alt="screenie_1519213025_279281" src="https://user-images.githubusercontent.com/334273/36478153-a5995524-16fb-11e8-9bcf-a25b903ee099.png">

**Comment by jluczak** [comment]
We are really sorry for the inconvenience! We are checking it with card payment operator.

**Comment by kaspergrubbe** [comment]
Hi @jluczak, thanks for your answer, have you verified with the card payment operator?

**Comment by jluczak** [comment]
@kaspergrubbe please, check if your tickets are visible now

**Comment by kaspergrubbe** [comment]
Hi @jluczak 

It is there, thank you very much, but there is still errors.

The tickets page shows a different order number, a different total price, and a different number of tickets. Compare these two screens: 

<img width="691" alt="screenie_1519230317_08238" src="https://user-images.githubusercontent.com/334273/36492060-203696e8-1724-11e8-9455-a7cd6e7b79a0.png">

<img width="850" alt="screenie_1519230332_390881" src="https://user-images.githubusercontent.com/334273/36492066-25799e0c-1724-11e8-9ae9-05743272ccfe.png">

**Comment by kaspergrubbe** [comment]
I can also transfer the tickets from that other order.

<img width="841" alt="screenie_1519230505_13023" src="https://user-images.githubusercontent.com/334273/36492304-c524c4a4-1724-11e8-8e7b-3c685f143336.png">

(I have been nice and removed that barcodes)

**Comment by kaspergrubbe** [comment]
And now my double tickets disappeared. Super strange.

**Comment by zaiste** [comment]
@kaspergrubbe I'm sorry for this situation. We are still in the process of investigating what happened. This new integration was a bit painful for us. 

By default we use Stripe. As you probably know Stripe isn't available in Poland (for sellers). We opted for a local provider which requires this external redirection. Thus, this process is slightly different. We rely on their statuses. It seems either we wrongly understood it or there's some deeper problem there. 

In the upcoming hours you may see some changes in your account as we go forward to clarify everything. We'll get back to you once we sort it out. 

Sorry again for the stress we caused you today.

**Comment by kaspergrubbe** [comment]
Hi @zaiste 

Thank you so much for your explanation, I am glad that you are sorting out the issues. I have my ticket, and I am pleased 🥇
