### ISSUE TITLE
I entered wrong invoice data - how do I change it?

### ISSUE THREAD

**Issue by wzin** [eventil/eventil.com#157]
Hello,

while purchasing an order for wrocloverb tickets I submitted wrong invoice data. How do I change it?

Thanks

**Comment by DianaGawel** [comment]
@wzin Hi, please provide us with the correct data. We will correct the invoice

**Comment by ligezantoni** [comment]
I also would like to change invoice data, who should I provide with correct data so it could be changed?

**Comment by DianaGawel** [comment]
@ligezantoni Please send me an email to diana@eventil.com

**Comment by ligezantoni** [comment]
@DianaGawel I've sent an email, when can I expect changes to be made?

**Comment by DianaGawel** [comment]
@ligezantoni Yes, don't worry. The changes will be made, give us some time. I will send you an e-mail once the data is corrected

**Comment by DianaGawel** [comment]
@wzin I got your e-mail. We will correct the data and I will get back to you once it's done.

**Comment by DianaGawel** [comment]
@ligezantoni changes for you are completed
