### ISSUE TITLE
Can't see previously bought tickets to the same event

### ISSUE THREAD

**Issue by marostr** [eventil/eventil.com#158]
Hey

I've bought few tickets to the same event separately, received confirmations but I can see only the last one on attendee tickets page.

**Comment by ligezantoni** [comment]
I have the same problem. I have printscreened QR codes of previous tickets, although I doubt if they are valid if they are not visible on site.

**Comment by jluczak** [comment]
@marostr @ligezantoni We are really sorry for the inconvenience!  We're working on it right now. Please do not worry, your tickets will be available for you soon!

**Comment by marostr** [comment]
@jluczak my tickets are back but "Buyer info" on Invoice is missing company data (name, tax number)

**Comment by jluczak** [comment]
@marostr please send all data here, so we could update it

**Comment by DianaGawel** [comment]
@marostr I got your e-mail. We will change the data. I will get to you once it's done.

**Comment by DianaGawel** [comment]
@marostr The data is corrected on your invoices
