### ISSUE TITLE
No order number (invoice number) on my document

### ISSUE THREAD

**Issue by gotar** [eventil/eventil.com#159]
I just ordered ticket for wroclove.rb 2018, and got it. But order confirmation (invoice) do not include necessary number. 

Order id: bPzVYQ3aXmoe1eBpLdqD

Can you fix it?

**Comment by kaspergrubbe** [comment]
And if it is anything like mine, the total is different than the order lines, so I suspect that they are not adding their fee.

<img width="478" alt="screenie_1519218205_8760939" src="https://user-images.githubusercontent.com/334273/36481544-110f57ca-1708-11e8-8d8c-25e609a1c0e9.png">

**Comment by DianaGawel** [comment]
@gotar We will check it and get to you as soon as possible

**Comment by gotar** [comment]
@kaspergrubbe Missing part on your order is VAT (23%), on mine it's just missing (empty space) in place where order number should be

**Comment by DianaGawel** [comment]
@gotar Invoice number available, please check
