### ISSUE TITLE
Typo in invoice

### ISSUE THREAD

**Issue by torrocus** [eventil/eventil.com#160]
We just ordered ticket for wroclove.rb 2018 and we got invoice with typo. At the bottom of the invoice is information about exchange rate. In this case it is "Echanged tax amount" instead "Exchanged tax amount". Is this related to your platform or did the organizer make a typo?

**Comment by DianaGawel** [comment]
@torrocus Thank you for informing us, we will check the case

**Comment by DianaGawel** [comment]
@torrocus Hi, it's corrected.
