### ISSUE TITLE
Cannot reset password

### ISSUE THREAD

**Issue by matkowal** [eventil/eventil.com#161]
I got a ticket for Wroclove.rb 2018 through eventil, and so an account was automatically created for me there. When I click on the link with the token from the email message and try to reset the password in order to download the ticket it doesn't let me. No matter how many characters I type in, the form is always complaining about 8 characters minimum ¯\_(ツ)_/¯ I'm pretty sure that 12 > 8. Can you look into this? Thanks.

**Comment by DianaGawel** [comment]
@matkowal It seems that links from mails we’ve send you contained wrong tokens. Would you mind reseting your passwords through this link -> eventil.com/forgot/new and let us know if it’s ok?
