### ISSUE TITLE
Error: I can't upload organization photo

### ISSUE THREAD

**Issue by piecioshka** [eventil/eventil.com#174]
When I upload avatar of my organization submit button is enter in disable state.

in DevTools Console I can see that error:

```
Uncaught TypeError: Cannot set property 'innerHTML' of null
    at Image.r.onload (image_upload.js:58)
```

**Comment by tomkuk** [comment]
@piecioshka it should be fixed

**Comment by piecioshka** [comment]
Confirm. Thanks! 🎉
