### ISSUE TITLE
Pytanie: Jak uzupełnić zakładkę "Overview"?

### ISSUE THREAD

**Issue by piecioshka** [eventil/eventil.com#178]
Co muszę zrobić aby uzupełnić zakładkę "Overview" na profilu grupy: https://eventil.com/groups/warsawjs ?

**Comment by 2can** [comment]
@piecioshka it's been modified to display excerpt of group events, is it ok for you ?

**Comment by piecioshka** [comment]
@2can It's awesome! Maybe you can add a new section with random "Speakers"? List with 4 items.
