### ISSUE TITLE
Error: Description field is not supported Markdown

### ISSUE THREAD

**Issue by piecioshka** [eventil/eventil.com#181]
On page
https://eventil.com/events/warsawjs-workshop-24-testowanie-kodu-3-3-testy-integracyjne/edit
`Description` field is not supports markdown 😢

**Comment by piecioshka** [comment]
Still doesn't works:https://eventil.com/events/warsawjs-workshop-24-testowanie-kodu-3-3-testy-integracyjne
You can see at the bottom: `# test [a](https://google.pl)`

@tomkuk @zaiste

**Comment by tomkuk** [comment]
@piecioshka it should be ok right now

**Comment by piecioshka** [comment]
Thanks! 🍻
