### ISSUE TITLE
Error: Hardcoded currency

### ISSUE THREAD

**Issue by piecioshka** [eventil/eventil.com#182]
On page https://eventil.com/settings/attendee/tickets I can saw tickets which always has currency EUR, but I pay in PLN currency.

**Comment by 2can** [comment]
@piecioshka could you provide order ID ?

![screenshot](https://user-images.githubusercontent.com/779644/44987799-c1678480-af88-11e8-84e3-3e4b13709f54.png)

**Comment by piecioshka** [comment]
@2can sure! Order ID `OT09DWQAvZY3L5zpNmkKLa`

**Comment by 2can** [comment]
@piecioshka this should be fixed now

**Comment by piecioshka** [comment]
@2can Thanks
