### ISSUE TITLE
Error: Hardcoded name "Header"

### ISSUE THREAD

**Issue by piecioshka** [eventil/eventil.com#183]
On page https://eventil.com/events/warsawjs-workshop-24-testowanie-kodu-3-3-testy-integracyjne/orders/09DWQAvZY3L5zpNmkKLa/tickets_summary I static name of header called "Header" 😄

**Comment by 2can** [comment]
@piecioshka should be fixed now

**Comment by piecioshka** [comment]
@2can Great! 🚗
