### ISSUE TITLE
Error: Export or Import in Data Collection works incorrectly

### ISSUE THREAD

**Issue by piecioshka** [eventil/eventil.com#184]
When I `Export` Data Collection, next click `Remove All`, after all `Import` previous exported yaml file, structure of `Select Field`s and `Radio Button`s is not properly rendered.

At start I have list of 5 elements, after export and import, the same list is has single element.

**Comment by tomkuk** [comment]
@piecioshka could you share the file you are trying to upload ?

**Comment by piecioshka** [comment]
@tomkuk sure! https://gist.github.com/piecioshka/590c577c8b4c601e9ce0f640585f7fdc

**Comment by tomkuk** [comment]
@piecioshka this should be fixed now

**Comment by piecioshka** [comment]
Ok, I can't test because registration was opened today's morning.

**Comment by piecioshka** [comment]
Thanks!
