### ISSUE TITLE
Feature: "Update" button in Preorders

### ISSUE THREAD

**Issue by piecioshka** [eventil/eventil.com#187]
On page https://eventil.com/events/warsawjs-workshop-24-testowanie-kodu-3-3-testy-integracyjne/manage/preorders can I have a button "Update" on each row of preorder?

That feature allows me to update name / surname (when is missing, but is require for me, to sing certificates) or email when they have a typo (known case)

**Comment by 2can** [comment]
@piecioshka it's done, you can edit preorders only in `is_new` status

![screenshot](https://user-images.githubusercontent.com/779644/45763197-4cef3f80-bc30-11e8-8ecb-f9855fa42157.gif)

**Comment by piecioshka** [comment]
Thanks
