### ISSUE TITLE
Using without a Github account

### ISSUE THREAD

**Issue by justinxreese** [eventil/eventil.com#2]
It'd be nice to have an alternative to Github authentication on the auth page - even if it is a link to a Google form in the interim. I'm worried about potentially eliminating submissions from beginners or people not working as software engineers. Finding about this on the authentication page will probably be too late in the process and cause the person to be confused and leave.

Easiest solution I see is to make the current "Submit Talk" on `events/event-name` say "Submit a Talk with GitHub" and a second button that is the alternate process.

**Comment by zaiste** [comment]
@justinxreese we could add a regular registration (username, password, password confirmation) on top of Github OAuth. Would that work for you ?

**Comment by justinxreese** [comment]
Absolutely. Looking forward to trying this out.

**Comment by zaiste** [comment]
@justinxreese it's implemented :)
