### ISSUE TITLE
Error: Bad UX of datetime picker

### ISSUE THREAD

**Issue by piecioshka** [eventil/eventil.com#201]
![zrzut ekranu 2018-09-07 o 19 02 10](https://user-images.githubusercontent.com/244935/45232678-93f44100-b2d0-11e8-9563-2bbf8b39a5f2.png)

This datetime calendar is so hard to manage.

1. Missing "Today" or "Now" option
2. Better UX of how to display of times:
* https://www.syncfusion.com/products/jsp/control/images/ejdatetime%20picker/datetimepicker.png
* https://help.syncfusion.com/aspnetmvc/datetimepicker/getting-started_images/getting-started_img1.png
* https://github.com/xdan/datetimepicker

**Comment by zaiste** [comment]
@piecioshka I've deployed a slight redesign. It is now more clear and unified. Let me know your thoughts.

**Comment by piecioshka** [comment]
It's nicer. Thanks!
