### ISSUE TITLE
Is it possible to merge two accounts?

### ISSUE THREAD

**Issue by dzienisz** [eventil/eventil.com#210]
Hey, I accidentally created two accounts and I have tickets bought on both of them.

Is it possible to merge them?

**Comment by zaiste** [comment]
@dzienisz Sure. Can you provide their handles ?

**Comment by dzienisz** [comment]
Can you send me email where I can send you this data?

sob., 15 wrz 2018, 09:15 użytkownik Zaiste <notifications@github.com>
napisał:

**Comment by zaiste** [comment]
@dzienisz You can paste it here as those handlers are public anyway OR send it to `hello@eventil.com`

**Comment by dzienisz** [comment]
ok
