### ISSUE TITLE
Error: Default banner contains old logo (or has bad quality)

### ISSUE THREAD

**Issue by piecioshka** [eventil/eventil.com#212]
Why default image of this events:
* https://eventil.com/events/warsawjs-workshop-26-javascript-dla-poczatkujacych
* https://eventil.com/events/warsawjs-workshop-25-react-js
* https://eventil.com/events/warsawjs-meetup-50
* https://eventil.com/events/warsawjs-meetup-51
* https://eventil.com/events/warsawjs-workshop-27-tdd-w-praktyce
has old logo?

Here you have recent version of our logo: https://www.dropbox.com/sh/4uuijvnrafp84ci/AAB_c8QeP9XS7ljjxbucUlQMa?dl=0

Maybe you can create feature when I can define default banner of WarsawJS events?

**Comment by 2can** [comment]
@piecioshka most of the events listed were created by our automated workers which search the Internet for Tech Events. Apparently the quality on the external sources influenced this.

We will update the events you've listed.

Yes, for the final solution we will add option in group settings to define default poster image for events.

**Comment by piecioshka** [comment]
@2can great!
