### ISSUE TITLE
Error: Markdown in Open Graph description is bad - #ConFrontJS

### ISSUE THREAD

**Issue by piecioshka** [eventil/eventil.com#213]
Kiedy udostępniam link do https://eventil.com/events/confrontjs-2018
to widzę markdowna https://www.dropbox.com/s/z9yiupep0ze3a8i/Zrzut%20ekranu%202018-09-25%20o%2012.59.53.png?dl=0

Używam narzędzia https://cards-dev.twitter.com/validator

**Comment by zaiste** [comment]
@piecioshka it is fixed. It will be deployed on `production` tomorrow morning cc @2can

**Comment by piecioshka** [comment]
Thanks!
