### ISSUE TITLE
Features & Errors: Submissions section

### ISSUE THREAD

**Issue by piecioshka** [eventil/eventil.com#214]
https://eventil.com/events/confrontjs-2018/manage/submissions

1. Cieszyłbym się aby w zakładce Labels była liczba, ile razy labelka została użyta.

2. W zakładce Submissions chciałbym widzieć labelki każdej z prelekcji

3. Brakuje mi na tej stronie filtrowania po typie zgłoszenia (Pending, Accepted, Rejected)

4. Gdy kliknę w dowolny talk, aby zobaczyć szczegóły, to z prawej strony wysuwa się boks, ale treść strony pod boksem skroluje się do góry (znowu brakuje `preventDefault()`)

5. Brakuje posortowania po liczbie gwiazdek

6. Filtrowanie po wpisanej frazie nie działa, kiedy używam dużych liter

**Comment by tomkuk** [comment]
@piecioshka punkty 2,3,4,5,6 zostały naprawione

**Comment by piecioshka** [comment]
Gites @tomkuk ! 🍺
