### ISSUE TITLE
LEGAL: name and firm's name appear without permission

### ISSUE THREAD

**Issue by avirap** [eventil/eventil.com#219]
Hello,

My name and firm's name appear without permission in an event:

https://eventil.com/events/when-bitcoin-rules-the-world-bac217ba-2fe5-41df-934b-581cec02c77c/

This is causing me and my firm great damage. Any mention of Dr. Avi Rapaport and Rapaport Flagship needs to be removed with great urgency.

Thank you for treating with high priority.

Kind regards,

Dr Avi R

**Comment by 2can** [comment]
@avirap the event has been removed
