### ISSUE TITLE
LEGAL: remove mention from Event

### ISSUE THREAD

**Issue by avirap** [eventil/eventil.com#220]
Hello,

The below event makes reference to Dr. Avihai (Avi) Rapaport and his firm Rapaport Flagship Limited.

https://eventil.com/events/when-bitcoin-rules-the-world-bac217ba-2fe5-41df-934b-581cec02c77c

The affiliation caused by you is causing Dr. Rapaport and Rapaport Flagship great damage.

We are hereby requesting that any mention of Dr. Avihai (Avi) Rapaport and Rapaport Flagship Limited be removed with great urgency.

Thank you very much.

Dr Avi Rapaport
Rapaport Flagship Limited
+41-78-713-7997

**Comment by 2can** [comment]
@avirap the event has been removed
