### ISSUE TITLE
Image URLs pointing to invalid domain (doesn't match cert)

### ISSUE THREAD

**Issue by ghost** [eventil/eventil.com#222]
<img width="1020" alt="Screenshot 2019-06-24 at 12 02 28" src="https://user-images.githubusercontent.com/31992054/60014134-2dca8600-9678-11e9-8e61-74540d81b3d7.png">
<img width="1078" alt="Screenshot 2019-06-24 at 12 02 20" src="https://user-images.githubusercontent.com/31992054/60014135-2dca8600-9678-11e9-80c6-6e53facd4a9a.png">

**Comment by ghost** [comment]
uh there's another - translations missing - 

<img width="706" alt="Screenshot 2019-06-24 at 12 13 36" src="https://user-images.githubusercontent.com/31992054/60014720-91a17e80-9679-11e9-9d49-86b01a440122.png">

**Comment by zaiste** [comment]
@bryanhuntesl All those issues should be now resolved. We were making some changes on the server to reduce the TTFB. It also covered a CDN switch. Thanks for reporting it!
