### ISSUE TITLE
Ticket Refund

### ISSUE THREAD

**Issue by polilluminato** [eventil/eventil.com#233]
Hi I bought a ticket for the Flutter Europe but sadly I can no longer attend the conference, how I can get a refund for the ticket purchased?

I send a mail also to @zaiste but the email zaiste@eventil.com seems to be not valid as stated in this other issue #218

**Comment by zaiste** [comment]
@polilluminato I believe we exchanged over email. Have you managed to contact the organizers ?

**Comment by polilluminato** [comment]
> @polilluminato I believe we exchanged over email. Have you managed to contact the organizers ?

Yeah! I contacted the organizer and they repaid my purchase.

Thanks,
Alberto
