### ISSUE TITLE
Several UI glitches on Firefox 46

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#24]
I've noticed several glitches on Firefox 46. See these screenshots:

![screen shot 2016-05-12 at 20 41 25](https://cloud.githubusercontent.com/assets/33736/15295558/8f9127b6-1b80-11e6-8a44-3d347d5acc18.png)

![screen shot 2016-05-12 at 20 42 18](https://cloud.githubusercontent.com/assets/33736/15295566/9627d458-1b80-11e6-9fed-10a1ddba024c.png)

**Comment by zaiste** [comment]
@deepj it's now corrected, please confirm

**Comment by deepj** [comment]
@zaiste the text field for putting in an email is okay. But the tooltip in memberlist not.

**Comment by 2can** [comment]
@deepj tooltip should be fixed, please confirm

**Comment by deepj** [comment]
@2can it's fixed! Great work!
