### ISSUE TITLE
Transform the rest of assets in PNG into SVG

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#38]
In "hero" section on homepages iPNG bitmaps are used for graphics (organiser, speaker, attendee) but the rest is in SVG vectors. The same case is default "person" in member list which is in PNG.

It would nice to unite everything into SVG only due to various HiDPI displays.

**Comment by zaiste** [comment]
@pawelwodkowski can you respond to this ?

**Comment by pawelwodkowski** [comment]
I have it on my to-do list.
