### ISSUE TITLE
Missing link to this support on Github

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#39]
It's unclear how to get to this GH issue tracker from the Eventil website.

**Comment by zaiste** [comment]
@deepj for now, we have added something simple to the footer, but it will be improved in the next sprint

![screen shot 2016-06-02 at 18 44 44](https://cloud.githubusercontent.com/assets/200613/15753205/2b99964c-28f2-11e6-8019-7b66b6d84a4e.png)

what do you think ?

**Comment by deepj** [comment]
@zaiste I guess it can be made by that way for now
