### ISSUE TITLE
Github Avatar problem

### ISSUE THREAD

**Issue by zaiste** [eventil/eventil.com#40]
From Daniel M.

> Pobieranie avatara z GitHuba chyba nie do końca działa, dałbym też tą opcję jako domyślnie włączoną.

**Comment by zaiste** [comment]
@hauleth what's the status of this ?

**Comment by hauleth** [comment]
IDK, should work.

## 

Łukasz Jan Niemier

Dnia 15 cze 2016 o godz. 10:59 Zaiste notifications@github.com napisał(a):
