### ISSUE TITLE
No padding in the footer on mobile devices (iPhone, iPad)

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#47]
There is no padding in the footer. See (an example from iPad):

![image](https://cloud.githubusercontent.com/assets/33736/15805433/796b0132-2b2a-11e6-8b8a-deb4844aa48e.png)

**Comment by deepj** [comment]
I noticed the same problem is in Safari.

**Comment by zaiste** [comment]
@kasiakasprzak what's the status of this ?

**Comment by kasiabernad** [comment]
@zaiste Didn't notice this issue - I didn't receive any notification via e-mail that I'm assigned. I have to create issue on our repo, estimate it and do it.
