### ISSUE TITLE
A map with all upcoming events

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#51]
Get an inspiration from http://lanyrd.com

**Comment by zaiste** [comment]
@deepj we have something like that: https://eventil.com/events/about/JavaScript/ but it's still a work-in-progress

**Comment by zaiste** [comment]
@deepj https://eventil.com/about/JavaScript/

**Comment by deepj** [comment]
@zaiste Where can I see a map with all events without any concrete focus of events?

**Comment by zaiste** [comment]
@deepj we're working on it, but we don't know yet how to incorporate into the whole application
