### ISSUE TITLE
DNS prefetching for external sources

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#52]
See [Controlling DNS prefetching](https://developer.mozilla.org/en-US/docs/Web/HTTP/Controlling_DNS_prefetching) on MDN.

This can help mainly with a speed of loading external sources on mobile devises. I recommend to you to put this into source code on top of `head` section (before loading any external source):

``` html
<link rel="dns-prefetch" href="//use.typekit.net">
<link rel="dns-prefetch" href="//cdnjs.cloudflare.com">
<link rel="dns-prefetch" href="//eventil.s3.amazonaws.com">
<link rel="dns-prefetch" href="//js.driftt.com">
<link rel="dns-prefetch" href="//event.api.driftt.com">
<link rel="dns-prefetch" href="//www.google-analytics.com">
<link rel="dns-prefetch" href="//maps.googleapis.com">
<link ref="dns-prefetch" href="//js.stripe.com">
```

**Comment by zaiste** [comment]
@deepj it's done on production
