### ISSUE TITLE
A group tile would keep same height without an image of event

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#54]
On https://eventil.com/groups See:

![screen shot 2016-06-05 at 19 21 15](https://cloud.githubusercontent.com/assets/33736/15807051/1f594a2e-2b42-11e6-9895-78443e537a2c.png)

**Comment by pawelwodkowski** [comment]
There should be blank img when no avatar.

**Comment by zaiste** [comment]
@deepj it seems you removed the `img` by hand, but when no avatar is provided during group creation, a default image will be displayed as pointed out by @pawelwodkowski 

Please confirm or reopen if needed

**Comment by deepj** [comment]
@zaiste it was ublock. Anyway, the tile should have a set height and doesn't depend on a height of an image + an image would have a generated name instead of keeping original one.
