### ISSUE TITLE
Force word break if a title in group profile doesn't fit the box

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#55]
See https://eventil.com/new-yorkkkkkkkkkkkkkkkkkkkk

![screen shot 2016-06-05 at 15 45 22](https://cloud.githubusercontent.com/assets/33736/15807525/16554e6a-2b50-11e6-992f-f170d318e7e9.png)

Take a look at:
https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/

**Comment by zaiste** [comment]
@deepj it's corrected
