### ISSUE TITLE
Enable HTTP/2

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#56]
Since the most assets are on S3 enabling support HTTP/2 on https://eventil.com doesn't help much in name of loading pages faster. But for sake of future you use NGINX 1.10 and enabling the support is super easy :).

See https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-with-http-2-support-on-ubuntu-16-04

**Comment by zaiste** [comment]
@deepj it's done
