### ISSUE TITLE
Word breaking of long event title on the event list

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#62]
I guess it's also needed to balance min/max width of particular parts in an event on the list. See:

![image](https://cloud.githubusercontent.com/assets/33736/15844049/5922ef0a-2c67-11e6-9824-7e4d05320fcf.png)

**Comment by zaiste** [comment]
@kasiakasprzak is this resolved ?

**Comment by kasiabernad** [comment]
@zaiste yes
