### ISSUE TITLE
Text fields have a shadow in desktop and not in mobile version

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#65]
See https://eventil.com/login

On the desktop text fields have a shadow. But not on mobile. I guess the shadow wouldn't be used.

**Comment by kasiabernad** [comment]
@deepj I have problem with replicate this bug. Which phone do you use to testing? When I use my phone (iPhone 5) I don't see shadow, but on Sony Xperia Z3 this shadow is visible. Also when I use phone emultor in my browser  there is no problem with shadow ( http://www.mobilephoneemulator.com ).

**Comment by deepj** [comment]
@kasiakasprzak The shadow is in the desktop version, not in mobile one. See:

With shadows – Safari 9.1 (Mac OS X 10.11):
![screen shot 2016-06-13 at 17 24 45](https://cloud.githubusercontent.com/assets/33736/16013015/5b799b14-317b-11e6-96bc-ff58c89c4b07.png)

No shadows — Safari 9 (iOS 9.3)
![img_6407](https://cloud.githubusercontent.com/assets/33736/16017455/7941926e-318f-11e6-8a15-23192d2021ba.jpg)

**Comment by zaiste** [comment]
@kasiakasprzak is this resolved ?

**Comment by kasiabernad** [comment]
@zaiste yes

**Comment by deepj** [comment]
@kasiakasprzak @zaiste Unfortunately, I'm still seeing it on the desktop.

**Comment by kasiabernad** [comment]
@deepj I fixed it in that way, that shadow is visible on the desktop and on the mobile version. This is how was it designed.
