### ISSUE TITLE
Not clear how to contact Eventil on the website

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#66]
I couldn't find a way how to contact Eventil support or something like that. There would be a way how to make it. A contact form anywhere?

**Comment by zaiste** [comment]
@deepj we're working on a new footer, we will add this once the footer is ready

**Comment by deepj** [comment]
@zaiste Where can I see a new footer?

**Comment by zaiste** [comment]
@deepj https://cloud.githubusercontent.com/assets/407311/16195857/c1bdbdf8-36fb-11e6-91a4-a6843c8a4805.png
