### ISSUE TITLE
Date overlaps a title of talk in an user profile on mobile

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#67]
https://eventil.com/users/stevenmcd

![image](https://cloud.githubusercontent.com/assets/33736/15893185/73284342-2d7e-11e6-98d6-b1b07c2eb715.png)

BTW: the right/left margin is too large.

**Comment by zaiste** [comment]
@kasiakasprzak is this resolved ?

**Comment by kasiabernad** [comment]
@zaiste yes

**Comment by zaiste** [comment]
@deepj could you confirm it's OK on your side ?

**Comment by deepj** [comment]
@zaiste it's okay
