### ISSUE TITLE
Some characters are undercut in registration

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#70]
It's same in Firefox and Safari (where it's more visible):

![screen shot 2016-06-10 at 08 55 40](https://cloud.githubusercontent.com/assets/33736/15956543/be1e57e6-2ed8-11e6-896a-4e050fd0206e.png)

**Comment by pawelwodkowski** [comment]
Not only in registration. This is bug common in every .list > .element > h3 instance.
I will work on this.

**Comment by zaiste** [comment]
@deepj is it still the case ?

**Comment by deepj** [comment]
No, I haven't noticed this kind of issues on the current version.
