### ISSUE TITLE
Does not let me log in into my account, says I need to confirm it

### ISSUE THREAD

**Issue by TamaraAtanasoska** [eventil/eventil.com#74]
Hello,

I have an account with an email address I used to buy a PolyConf ticket. I would like to print the ticket, but when I try to log in, it says that I need to confirm the email address before I can do that. Of course, the old confirmation link has expired and leads to a 404 now. 

Is there a resend confirmation link anywhere? Maybe if could be offered together with the "needs to be confirmed" error for the future?

For now, I just really want access so I can get my PolyConf ticket :)

Thanks!
Tamara

**Comment by tomkuk** [comment]
@TamaraAtanasoska please go to https://eventil.com/confirm/new and try to resend your confirmation link

**Comment by TamaraAtanasoska** [comment]
@tomkuk Thank you! That fixes it.

**Comment by nsh-ableton** [comment]
I had the same problem. Ironically, when searching for information on how to deal with this, I eventually found this issue, created by my colleague. 😆 

It would be helpful to have a link to the "Resend confirmation instructions" somewhere on the site.

**Comment by zaiste** [comment]
@tomkuk could you add a link on the website ?

**Comment by tomkuk** [comment]
@zaiste "resend confirmation link" has been added to forgot password page

**Comment by zaiste** [comment]
@TamaraAtanasoska @nsh-ableton is the addition of the « confirmation reset » link to forgot password OK for you ?

**Comment by nsh-ableton** [comment]
Hi @zaiste — I think what would be the best is to put it on the page that says confirmation is required. So it would go like this:
- registered user enters username and password
- the page appears that says "You need to confirm your account". That's where the button should appear.

I guess someone could eventually find it on the "forgot password" page, but it's not the first place I'd look.

**Comment by zaiste** [comment]
@nsh-ableton you're absolutely right. We'll amend it cc @tomkuk
