### ISSUE TITLE
The /me/tickets page does not say what I am supposed to do with the ticket

### ISSUE THREAD

**Issue by not-raspberry** [eventil/eventil.com#75]
![dupa_bilet](https://cloud.githubusercontent.com/assets/12380813/16059868/4060c54a-3285-11e6-83fd-1f4716c23f42.png)

I think I'm supposed to print it now.

There should be some "Print" button. I can print the order on the order page but not the ticket. Technically, I can print the whole page but that's probably not what we want.

**Comment by zaiste** [comment]
@not-raspberry we're still working on « print » feature, it'll be ready by the end of this week. Initially we imagined a use case where ticket holders show the ticket on their mobile phone (the design is responsive) to be followed by a dedicated mobile application for that.

**Comment by 2can** [comment]
@not-raspberry we've added 'SHOW TICKETS' which gives possibility to print ticket via subpage

**Comment by zaiste** [comment]
@not-raspberry I'm closing this, let me know if it's OK (and reopen if needed).
