### ISSUE TITLE
One event under multiple groups

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#82]
Sometimes some groups decide to hold an common event. So would be weird it under only one of them or multiple the same event in each group. This case is real. I know that of my city when local Python and Ruby hold this kind of event.

**Comment by zaiste** [comment]
@deepj we already have this implemented cf. https://eventil.com/events/phoenix-elixir-vs-rails-ruby-sf

**Comment by deepj** [comment]
@zaiste Cool! I haven't noticed it.
