### ISSUE TITLE
Remote meetups

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#88]
I guess a support of remote meetups will need some "refactoring" of an event page design for this :)

**Comment by zaiste** [comment]
@deepj could you elaborate how you see remote events ?

**Comment by deepj** [comment]
@zaiste They have no psychical location, but they can be limited by a language (both programming and natural). So the map here is useless. They can be eventually connected with some kind of online event platform (an example: https://www.bigmarker.com/remote-meetup/0-Crystal-Remote-Meetup). Can this be explained shortly this way?

Take a look at this https://twitter.com/RemoteMeetup there are some other remote meetups mentioned there.

**Comment by tomkuk** [comment]
@deepj this should be fixed, there is location type to choose - `Onsite` / `Online` during new new event creation. Is it something you were looking for ?

**Comment by deepj** [comment]
@tomkuk yes. I guess this can be closed
