### ISSUE TITLE
Text in text fields are undercut in Firefox 47

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#93]
An example:

![screen shot 2016-06-22 at 17 34 08](https://cloud.githubusercontent.com/assets/33736/16272845/e2a80994-388e-11e6-9fbc-13456f90c971.png)

**Comment by deepj** [comment]
Notice the search button. The position of the text is weird.

**Comment by pawelwodkowski** [comment]
And there is height difference between User name and Interested in input.
Also "Interested in" don't have shadow but probably we could wait with this because we were supposed to redesign forms.

**Comment by deepj** [comment]
@pawelwodkowski OK. But there is more issues in this one. See the g in VP of Marketing:

![screen shot 2016-06-22 at 20 04 35](https://cloud.githubusercontent.com/assets/33736/16277812/ffdad41e-38a3-11e6-86ec-e9260152cf17.png)

**Comment by deepj** [comment]
It's still there

![screen shot 2016-09-30 at 12 47 49](https://cloud.githubusercontent.com/assets/33736/18989439/862dee02-86fb-11e6-9028-2f03c520febb.png)

**Comment by kasiabernad** [comment]
@deepj Maybe it's not deployed yet.
