### ISSUE TITLE
Don't use underline for word highlighting

### ISSUE THREAD

**Issue by deepj** [eventil/eventil.com#95]
![screen shot 2016-06-23 at 09 30 37](https://cloud.githubusercontent.com/assets/33736/16295204/e56e6c6e-3914-11e6-8b54-ce6ce4d347cb.png)

It isn't clear here what's a link or not. It's very confusing. Mainly on a iPad where is no cursor.

**Comment by pawelwodkowski** [comment]
I agree with @deepj
Only Login with Github should have been underlined.

**Comment by tomkuk** [comment]
I propose to replace it with bold text
